title: LutaML
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Lutaml’ uml domain specific language syntax.
# baseurl: "" # the subpath of your site, e.g. /blog

github_repo_url: https://https://github.com/lutaml/lutaml.github.io
github_repo_branch: main

theme: jekyll-theme-open-project

landing_priority: [custom_intro, blog, specs, software]

author:
  name: Ribose Inc.
  url: https://www.ribose.com

authors:
  - name: Ribose Inc.
    email: open.source@ribose.com

contact_email: open.source@ribose.com

# parent_hub:
#   git_repo_url: https://github.com/riboseinc/open.ribose.com
#   git_repo_branch: main
#   home_url: https://open.ribose.com/

includes_dir: '.'

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/lutaml/lutaml

legal:
  name: Ribose Group Inc.
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

home_calls_to_action:
  - { url: "/specs/", title: "Uml domain specific language" }

collections:
  projects:
    output: false
  software:
    output: true
    permalink: /software/:path/
  specs:
    output: true
    permalink: /specs/:path/
  posts:
    output: true
    permalink: /blog/:year-:month-:day-:title/
  pages:
    output: true
    permalink: /:name/


defaults:
  # Theme defaults.
  # MUST be duplicated from theme’s _config.yml
  # (does not get inherited, unlike the collections hash)
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  - scope:
      path: _software
      type: software
    values:
      layout: product
  - scope:
      path: _specs
      type: specs
    values:
      layout: spec

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

tag_namespaces:
  software:
    writtenin: "Written in"
    bindingsfor: "Bindings for"
    user: "Target user"
    interface: "Interface"
  specs:
    audience: "Audience"
    completion_status: "Status"

include:
  - "index.adoc"
  - "404.html"

exclude:
  - .git
  - .lycheeignore
  - "*/.git"
  - Gemfile*
  - Makefile
  - Rakefile
  - README.adoc
  - vendor # for deployment
